name: CodeQL

on:
  push:
    branches:
      - develop
      - main
    paths:
      - 'pages/**'
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'yarn.lock'
  pull_request:
    branches:
      - develop
    paths:
      - 'pages/**'
      - 'src/**'
      - 'test/**'
      - 'package.json'
      - 'yarn.lock'
  schedule:
    # run every day at 1AM
    - cron: "0 1 * * *"

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-20.04

    steps:
    -
      name: Checkout repository
      uses: actions/checkout@v2.3.4

    -
      name: Initialize CodeQL
      uses: github/codeql-action/init@v1
      with:
        languages: 'javascript'

    -
      name: Autobuild
      uses: github/codeql-action/autobuild@v1

    -
      name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v1
